### ISSUE TITLE
PacMan

### ISSUE THREAD

**Issue by maxiostro** [csf30816/scratchviewer#1]
http://scratch.mit.edu/projects/50210362/
http://scratchviewer.usa.cc/#50210362
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by csf30816** [comment]
Hi, sorry I am late in response. I know the problem and I am working on fixing it now... Thanks for your patients.

**Comment by csf30816** [comment]
Fixed
